In [571]:
import numpy as np
import pandas as pd
import math

In [572]:
batch_size = 10
in_size = 257
h1_size = 769
h2_size = 192
h3_size = 30
out_size = 10

# LOAD IN ALL VALUES

In [573]:
W_h1 = np.fromfile("W_h1", dtype=np.float32)
W_h1_full = np.fromfile("W_h1_full", dtype=np.float32)
W_h2 = np.fromfile("W_h2", dtype=np.float32)
W_h2_full = np.fromfile("W_h2_full", dtype=np.float32)
W_h3 = np.fromfile("W_h3", dtype=np.float32)
W_out = np.fromfile("W_out", dtype=np.float32)

In [574]:
W_h1 = np.reshape(W_h1, (300, 1))
W_h1_full = np.reshape(W_h1_full, (h1_size, in_size))
W_h2 = np.reshape(W_h2, (2400, 1))
W_h2_full = np.reshape(W_h2_full, (h2_size, h1_size))
W_h3 = np.reshape(W_h3, (h3_size, h2_size))
W_out = np.reshape(W_out, (out_size, h3_size))

In [575]:
B_h1 = np.fromfile("B_h1", dtype=np.float32)
B_h2 = np.fromfile("B_h2", dtype=np.float32)
B_h3 = np.fromfile("B_h3", dtype=np.float32)
B_out = np.fromfile("B_out", dtype=np.float32)

In [576]:
B_h1 = np.reshape(B_h1, (h1_size, 1))
B_h2 = np.reshape(B_h2, (h2_size, 1))
B_h3 = np.reshape(B_h3, (h3_size, 1))
B_out = np.reshape(B_out, (out_size, 1))

In [577]:
A_h1 = np.fromfile("A_h1", dtype=np.float32)
A_h2 = np.fromfile("A_h2", dtype=np.float32)
A_h3 = np.fromfile("A_h3", dtype=np.float32)
A_out = np.fromfile("A_out", dtype=np.float32)

In [578]:
A_h1 = np.reshape(A_h1, (h1_size, batch_size))
A_h2 = np.reshape(A_h2, (h2_size, batch_size))
A_h3 = np.reshape(A_h3, (h3_size, batch_size))
A_out = np.reshape(A_out, (out_size, batch_size))

In [579]:
X_in = np.fromfile("X_in", dtype=np.float32)
X_h1 = np.fromfile("X_h1", dtype=np.float32)
X_h2 = np.fromfile("X_h2", dtype=np.float32)
X_h3 = np.fromfile("X_h3", dtype=np.float32)
X_out = np.fromfile("X_out", dtype=np.float32)
Y_out = np.fromfile("Y_out", dtype=np.float32)

In [580]:
X_in = np.reshape(X_in, (in_size, batch_size))
X_h1 = np.reshape(X_h1, (h1_size, batch_size))
X_h2 = np.reshape(X_h2, (h2_size, batch_size))
X_h3 = np.reshape(X_h3, (h3_size, batch_size))
X_out = np.reshape(X_out, (out_size, batch_size))
Y_out = np.reshape(Y_out, (out_size, batch_size))

In [581]:
dW_h1 = np.fromfile("dW_h1", dtype=np.float32)
dW_h2 = np.fromfile("dW_h2", dtype=np.float32)
dW_h3 = np.fromfile("dW_h3", dtype=np.float32)
dW_out = np.fromfile("dW_out", dtype=np.float32)

In [582]:
dW_h1 = np.reshape(dW_h1, (300, 1))
dW_h2 = np.reshape(dW_h2, (2400, 1))
dW_h3 = np.reshape(dW_h3, (h3_size, h2_size))
dW_out = np.reshape(dW_out, (out_size, h3_size))

In [583]:
dX_h1 = np.fromfile("dX_h1", dtype=np.float32)
dX_h2 = np.fromfile("dX_h2", dtype=np.float32)
dX_h3 = np.fromfile("dX_h3", dtype=np.float32)
dX_out = np.fromfile("dX_out", dtype=np.float32)

In [584]:
softmax_jacobian = np.fromfile("softmax_jacobian", dtype=np.float32)
softmax_jacobian = np.reshape(softmax_jacobian, (batch_size, out_size, out_size))

In [585]:
dX_h1 = np.reshape(dX_h1, (h1_size, batch_size))
dX_h2 = np.reshape(dX_h2, (h2_size, batch_size))
dX_h3 = np.reshape(dX_h3, (h3_size, batch_size))
dX_out = np.reshape(dX_out, (out_size, batch_size))

In [586]:
dX_h1_activation = np.fromfile("dX_h1_activation", dtype=np.float32)
dX_h2_activation = np.fromfile("dX_h2_activation", dtype=np.float32)
dX_h3_activation = np.fromfile("dX_h3_activation", dtype=np.float32)
dX_out_activation = np.fromfile("dX_out_activation", dtype=np.float32)

In [587]:
dX_h1_activation = np.reshape(dX_h1_activation, (h1_size, batch_size))
dX_h2_activation = np.reshape(dX_h2_activation, (h2_size, batch_size))
dX_h3_activation = np.reshape(dX_h3_activation, (h3_size, batch_size))
dX_out_activation = np.reshape(dX_out_activation, (out_size, batch_size))

In [588]:
sec_dX_h1_activation = np.fromfile("sec_dX_h1_activation", dtype=np.float32)
sec_dX_h2_activation = np.fromfile("sec_dX_h2_activation", dtype=np.float32)
sec_dX_h3_activation = np.fromfile("sec_dX_h3_activation", dtype=np.float32)
sec_dX_out_activation = np.fromfile("sec_dX_out_activation", dtype=np.float32)

In [589]:
sec_dX_h1_activation = np.reshape(sec_dX_h1_activation, (h1_size, batch_size))
sec_dX_h2_activation = np.reshape(sec_dX_h2_activation, (h2_size, batch_size))
sec_dX_h3_activation = np.reshape(sec_dX_h3_activation, (h3_size, batch_size))
sec_dX_out_activation = np.reshape(sec_dX_out_activation, (out_size, batch_size))

In [590]:
W_h1_norm = np.fromfile("B_h1_norm", dtype=np.float32)[0]
W_h2_norm = np.fromfile("B_h2_norm", dtype=np.float32)[0]
W_h3_norm = np.fromfile("B_h3_norm", dtype=np.float32)[0]
W_out_norm = np.fromfile("B_out_norm", dtype=np.float32)[0]

In [591]:
B_h1_norm = np.fromfile("B_h1_norm", dtype=np.float32)[0]
B_h2_norm = np.fromfile("B_h2_norm", dtype=np.float32)[0]
B_h3_norm = np.fromfile("B_h3_norm", dtype=np.float32)[0]
B_out_norm = np.fromfile("B_out_norm", dtype=np.float32)[0]

In [592]:
sec_dW_h1 = np.fromfile("sec_dW_h1", dtype=np.float32)
sec_dW_h2 = np.fromfile("sec_dW_h2", dtype=np.float32)
sec_dW_h3 = np.fromfile("sec_dW_h3", dtype=np.float32)
sec_dW_out = np.fromfile("sec_dW_out", dtype=np.float32)

In [593]:
sec_dW_h1 = np.reshape(sec_dW_h1, (300, 1))
sec_dW_h2 = np.reshape(sec_dW_h2, (2400, 1))
sec_dW_h3 = np.reshape(sec_dW_h3, (h3_size, h2_size))
sec_dW_out = np.reshape(sec_dW_out, (out_size, h3_size))

In [594]:
sec_dB_h1 = np.fromfile("sec_dB_h1", dtype=np.float32)
sec_dB_h2 = np.fromfile("sec_dB_h2", dtype=np.float32)
sec_dB_h3 = np.fromfile("sec_dB_h3", dtype=np.float32)
sec_dB_out = np.fromfile("sec_dB_out", dtype=np.float32)

In [595]:
sec_dB_h1 = np.reshape(sec_dB_h1, (h1_size, 1))
sec_dB_h2 = np.reshape(sec_dB_h2, (h2_size, 1))
sec_dB_h3 = np.reshape(sec_dB_h3, (h3_size, 1))
sec_dB_out = np.reshape(sec_dB_out, (out_size, 1))

In [596]:
W_h1_step = np.fromfile("W_h1_step", dtype=np.float32)
W_h2_step = np.fromfile("W_h2_step", dtype=np.float32)
W_h3_step = np.fromfile("W_h3_step", dtype=np.float32)
W_out_step = np.fromfile("W_out_step", dtype=np.float32)

In [597]:
W_h1_step = np.reshape(W_h1_step, (300, 1))
W_h2_step = np.reshape(W_h2_step, (2400, 1))
W_h3_step = np.reshape(W_h3_step, (h3_size, h2_size))
W_out_step = np.reshape(W_out_step, (out_size, h3_size))

In [598]:
B_h1_step = np.fromfile("B_h1_step", dtype=np.float32)
B_h2_step = np.fromfile("B_h2_step", dtype=np.float32)
B_h3_step = np.fromfile("B_h3_step", dtype=np.float32)
B_out_step = np.fromfile("B_out_step", dtype=np.float32)

In [599]:
B_h1_step = np.reshape(B_h1_step, (h1_size, 1))
B_h2_step = np.reshape(B_h2_step, (h2_size, 1))
B_h3_step = np.reshape(B_h3_step, (h3_size, 1))
B_out_step = np.reshape(B_out_step, (out_size, 1))

In [601]:
W_h3_norm

2.9436138

### DEBUG (WHERE IS SHE GOING WRONG???)

In [602]:
def my_tanh_activ(in_arr):
    rows = in_arr.shape[0]
    cols = in_arr.shape[1]
    activ = np.empty((rows, cols))
    for i in range(rows):
        for j in range(cols):
            val = in_arr[i, j]
            activ[i, j] = 1.7159 * math.tanh((2.0 / 3) * val)
    return activ

In [603]:
def my_softmax(in_arr):
    classes = in_arr.shape[0]
    batch_size = in_arr.shape[1]
    out = np.empty((classes, batch_size))
    for samp in range(batch_size):
        s = 0
        for c in range(classes):
            s += np.exp(in_arr[c, samp])
        for c in range(classes):
            out[c, samp] = np.exp(in_arr[c, samp]) / s
    return out

In [604]:
def my_softmax_jacobian(in_arr):
    classes = in_arr.shape[0]
    batch_size = in_arr.shape[1]
    jacobian = np.empty((batch_size, classes, classes))
    for samp in range(batch_size):
        for i in range(classes):
            for j in range(classes):
                if i == j:
                    jacobian[samp, i, j] = in_arr[i, samp] * (1 - in_arr[i, samp])
                else:
                    jacobian[samp, i, j] = -1 * in_arr[i, samp] * in_arr[j, samp]
    return jacobian

In [605]:
def my_activation_deriv_soft(gradient, jacobian):
    classes = gradient.shape[0]
    batch_size = gradient.shape[1]
    activ_deriv = np.empty((classes, batch_size))
    for samp in range(batch_size):
        for i in range(classes):
            s = 0
            for k in range(classes):
                s += gradient[k, samp] * jacobian[samp, i, k]
            activ_deriv[i, samp] = s
    return activ_deriv

In [606]:
def softmax_second_deriv(in_arr):
    rows = in_arr.shape[0]
    cols = in_arr.shape[1]
    secDeriv = np.empty((rows, cols))
    for i in range(rows):
        for j in range(cols):
            secDeriv[i, j] = in_arr[i, j] * (1 - in_arr[i, j])
    return secDeriv

In [624]:
np.mean(X_in)

-0.72151375

In [239]:
activ_h1 = my_tanh_activ(A_h1)

In [240]:
fakeA_out = W_out @ X_h3 + B_out

In [241]:
fakeX_out = softmax(A_out)

In [246]:
Y_out

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [242]:
fakeX_out

array([[0.0625987 , 0.05877733, 0.0520235 , 0.04787069, 0.06897437,
        0.1525177 , 0.11772489, 0.04606903, 0.04245582, 0.02399107],
       [0.22371797, 0.18675048, 0.20421109, 0.06756522, 0.14903544,
        0.03303778, 0.04198031, 0.26315192, 0.34423457, 0.52845881],
       [0.11797547, 0.13424953, 0.12872319, 0.10060536, 0.12541068,
        0.08954452, 0.06856954, 0.12952052, 0.10417882, 0.08736992],
       [0.11166087, 0.07878829, 0.11005365, 0.08509234, 0.08800875,
        0.12375522, 0.14061136, 0.10360302, 0.08287004, 0.06867951],
       [0.07845688, 0.0975673 , 0.0751626 , 0.19976036, 0.0922534 ,
        0.10623627, 0.09567904, 0.07564908, 0.0535683 , 0.03422606],
       [0.06661036, 0.06212261, 0.07431718, 0.06725134, 0.06912485,
        0.09808704, 0.10877172, 0.05494497, 0.05534071, 0.03425657],
       [0.10641769, 0.13526247, 0.10013531, 0.14439341, 0.12392239,
        0.09336742, 0.06572107, 0.11920122, 0.08699162, 0.07120648],
       [0.08189807, 0.09191853, 0.0787867

In [245]:
X_out

array([[0.06259869, 0.05877733, 0.0520235 , 0.04787069, 0.06897438,
        0.15251769, 0.1177249 , 0.04606902, 0.04245582, 0.02399107],
       [0.22371797, 0.18675047, 0.20421113, 0.06756523, 0.14903547,
        0.03303778, 0.04198031, 0.26315188, 0.34423456, 0.52845883],
       [0.11797547, 0.13424954, 0.1287232 , 0.10060536, 0.12541069,
        0.08954451, 0.06856955, 0.1295205 , 0.10417882, 0.08736993],
       [0.11166086, 0.0787883 , 0.11005365, 0.08509234, 0.08800875,
        0.12375522, 0.14061135, 0.10360301, 0.08287004, 0.0686795 ],
       [0.07845689, 0.0975673 , 0.0751626 , 0.19976035, 0.09225341,
        0.10623626, 0.09567904, 0.07564908, 0.0535683 , 0.03422606],
       [0.06661036, 0.06212261, 0.07431719, 0.06725133, 0.06912486,
        0.09808704, 0.10877173, 0.05494496, 0.05534071, 0.03425657],
       [0.10641769, 0.13526247, 0.10013531, 0.14439341, 0.1239224 ,
        0.09336742, 0.06572107, 0.11920121, 0.08699162, 0.0712065 ],
       [0.08189806, 0.09191854, 0.0787867

In [608]:
my_jacobian = my_softmax_jacobian(X_out)

In [609]:
my_jacobian[0]

array([[-0.03526664,  0.02297663,  0.00123604,  0.00120966, -0.0052218 ,
        -0.00191766,  0.00459081, -0.00077806,  0.00884017,  0.00156684],
       [ 0.02297663,  0.21981761, -0.02441841, -0.02389744,  0.10315894,
         0.03788412, -0.09069342,  0.01537091, -0.17464133, -0.03095367],
       [ 0.00123604, -0.02441841,  0.03492998, -0.00128557,  0.00554947,
         0.00203799, -0.00487888,  0.00082688, -0.00939489, -0.00166516],
       [ 0.00120966, -0.02389744, -0.00128557,  0.03421216,  0.00543107,
         0.00199451, -0.00477479,  0.00080924, -0.00919445, -0.00162964],
       [-0.0052218 ,  0.10315894,  0.00554947,  0.00543107, -0.17656045,
        -0.00860976,  0.02061151, -0.00349328,  0.03969   ,  0.00703471],
       [-0.00191766,  0.03788412,  0.00203799,  0.00199451, -0.00860976,
        -0.05939221,  0.00756938, -0.00128287,  0.01457577,  0.00258343],
       [ 0.00459081, -0.09069342, -0.00487888, -0.00477479,  0.02061151,
         0.00756938,  0.11649288,  0.00307116

In [247]:
softmax_jacobian[0]

array([[ 0.05868009, -0.01400445, -0.00738511, -0.00698982, -0.0049113 ,
        -0.00416972, -0.00666161, -0.00512671, -0.00466656, -0.0047648 ],
       [-0.01400445,  0.17366824, -0.02639323, -0.02498054, -0.01755222,
        -0.01490193, -0.02380755, -0.01832207, -0.01667757, -0.01702867],
       [-0.00738511, -0.02639323,  0.10405726, -0.01317324, -0.00925599,
        -0.00785839, -0.01255468, -0.00966196, -0.00879475, -0.0089799 ],
       [-0.00698982, -0.02498054, -0.01317324,  0.09919272, -0.00876056,
        -0.00743777, -0.01188269, -0.00914481, -0.00832401, -0.00849925],
       [-0.0049113 , -0.01755222, -0.00925599, -0.00876056,  0.0723014 ,
        -0.00522604, -0.0083492 , -0.00642547, -0.00584875, -0.00597188],
       [-0.00416972, -0.01490193, -0.00785839, -0.00743777, -0.00522604,
         0.06217342, -0.00708852, -0.00545526, -0.00496562, -0.00507016],
       [-0.00666161, -0.02380755, -0.01255468, -0.01188269, -0.0083492 ,
        -0.00708852,  0.09509297, -0.0087154 

In [464]:
X_out

array([[0.08925878, 0.08889606, 0.12766595, 0.11296537, 0.20019475,
        0.14092053, 0.14192222, 0.12775329, 0.14536503, 0.07390672],
       [0.08957201, 0.13120301, 0.05189087, 0.12591673, 0.0566518 ,
        0.08011059, 0.079431  , 0.0906648 , 0.05936025, 0.12427244],
       [0.06105398, 0.10024009, 0.06656912, 0.16183977, 0.1147434 ,
        0.12650572, 0.08724198, 0.12380946, 0.15019538, 0.06352715],
       [0.10688505, 0.13372275, 0.11967024, 0.12886088, 0.13369322,
        0.09956072, 0.115175  , 0.13950253, 0.13185243, 0.10784954],
       [0.16330922, 0.10122594, 0.14699067, 0.05863852, 0.06590062,
        0.08606255, 0.10361956, 0.0775246 , 0.07211641, 0.14247756],
       [0.09656812, 0.08146655, 0.11427972, 0.07601424, 0.10127148,
        0.09196494, 0.09691378, 0.09421347, 0.0970476 , 0.08282027],
       [0.07437302, 0.07683045, 0.07448577, 0.09958884, 0.08023824,
        0.1109391 , 0.08220668, 0.09032877, 0.11103949, 0.07178737],
       [0.09778228, 0.09846956, 0.083497 

In [463]:
Y_out

array([[0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [610]:
dX_out

array([[-0.03410358,  0.06907154, -0.14493439,  0.00984601,  0.09148291,
         0.09594077, -0.13898598, -0.02408113,  0.1360931 , -0.09288824],
       [-0.3262692 , -0.04981571, -0.44655198, -0.288967  , -0.1154201 ,
        -0.15252498, -0.14137527, -0.5577737 ,  0.11949975,  0.23902722],
       [ 0.03624357, -0.5324347 ,  0.16552198,  0.05989267,  0.15146452,
        -0.14603886, -0.16105486,  0.01352129,  0.2304196 , -0.05778806],
       [ 0.0354703 , -0.00736302,  0.44508144,  0.09901907, -0.48362368,
         0.17340447,  0.07920033,  0.04106402, -0.10077172,  0.15793362],
       [-0.15311596, -0.11545851, -0.16065267, -0.01116844, -0.02712696,
        -0.37266314, -0.329929  ,  0.08775997, -0.09071223, -0.65851235],
       [-0.05623036,  0.03964004, -0.07251501,  0.03244711, -0.01472639,
        -0.0293797 ,  0.17123434,  0.17708598, -0.59468246,  0.06968942],
       [ 0.13461374,  0.07985534,  0.04422081,  0.02185817, -0.15347934,
         0.10629322,  0.08203244,  0.08091711

In [611]:
dX_out_activation

array([[-0.03897755,  0.07872485, -0.16312113,  0.01126234,  0.10397979,
         0.10897624, -0.15663338, -0.027535  ,  0.15346867, -0.10555597],
       [-0.22865885, -0.05687773, -0.4292755 , -0.18598668, -0.1306847 ,
        -0.1713601 , -0.15924251, -0.5382505 ,  0.13520314,  0.26133618],
       [ 0.0414186 , -0.50197387, -0.10253269,  0.06832526,  0.17021182,
        -0.16432276, -0.18056251,  0.0154653 ,  0.2527599 , -0.06593686],
       [ 0.04053664, -0.00842246,  0.42842177,  0.11242062, -0.4331866 ,
         0.19377382,  0.09016499,  0.04691394, -0.11437949,  0.17720228],
       [-0.17199963, -0.13072729, -0.18012999, -0.01277473, -0.03101398,
        -0.28535283, -0.2329935 ,  0.09979966, -0.10311501, -0.6843366 ],
       [-0.06416824,  0.0452911 , -0.08261861,  0.03708746, -0.01684321,
        -0.03358625,  0.19146223,  0.19768523, -0.59155446,  0.07942385],
       [ 0.15184797,  0.09090338,  0.05051003,  0.02499516, -0.17239273,
         0.12053986,  0.09335634,  0.09209993

In [252]:
my_dX_out_activ = my_activation_deriv_soft(dX_out, softmax_jacobian)

In [329]:
W_h2

array([[-0.01337637],
       [ 0.00572512],
       [ 0.00910057],
       ...,
       [ 0.03248086],
       [-0.02303151],
       [ 0.05134966]], dtype=float32)

In [380]:
X_out

array([[0.08463813, 0.11203731, 0.09107924, 0.09136382, 0.08848689,
        0.0914972 , 0.09937358, 0.09016616, 0.09812659, 0.0894408 ],
       [0.1295389 , 0.10394011, 0.14511462, 0.11569617, 0.1258271 ,
        0.13012263, 0.11542963, 0.11649109, 0.10510141, 0.12236701],
       [0.09395782, 0.10705321, 0.10824035, 0.09319438, 0.0984033 ,
        0.10101824, 0.10444695, 0.09144088, 0.09701362, 0.0952976 ],
       [0.09639616, 0.11628019, 0.09265352, 0.10462394, 0.0939562 ,
        0.09355009, 0.11439992, 0.09501461, 0.12176774, 0.09881959],
       [0.10440499, 0.08303432, 0.0950911 , 0.10458504, 0.10718062,
        0.10135925, 0.08658844, 0.1124576 , 0.08752216, 0.10403299],
       [0.08468217, 0.09766331, 0.07823056, 0.08411524, 0.08150449,
        0.08098785, 0.0928577 , 0.07975888, 0.10283215, 0.08348272],
       [0.10268229, 0.09685405, 0.10494798, 0.09848896, 0.10508967,
        0.10535869, 0.09893812, 0.10314858, 0.09229439, 0.10139438],
       [0.09955179, 0.09010492, 0.0956328

In [466]:
secondDeriv = softmax_second_deriv(X_out)

In [615]:
W_h1

array([[ 0.03783344],
       [ 0.0803776 ],
       [ 0.00490003],
       [-0.12519005],
       [ 0.01827212],
       [-0.09256253],
       [-0.09131142],
       [ 0.06902752],
       [-0.13450256],
       [-0.12136352],
       [ 0.0411229 ],
       [ 0.10638256],
       [-0.06176207],
       [-0.02602325],
       [ 0.01967761],
       [ 0.13597862],
       [ 0.00256265],
       [ 0.07315338],
       [ 0.13962145],
       [ 0.1134902 ],
       [ 0.09736775],
       [ 0.10566284],
       [-0.06020095],
       [-0.12035025],
       [ 0.09435086],
       [ 0.0495363 ],
       [ 0.09664658],
       [-0.04811975],
       [ 0.01485579],
       [ 0.02795524],
       [ 0.15808268],
       [-0.11211584],
       [-0.1009003 ],
       [-0.08451113],
       [ 0.1154925 ],
       [ 0.01896596],
       [-0.14152326],
       [-0.13205636],
       [-0.08598739],
       [ 0.0878718 ],
       [ 0.02469275],
       [-0.14185224],
       [-0.07832223],
       [ 0.11676299],
       [-0.05387843],
       [-0

In [621]:
dX_out_activation

array([[-0.03897755,  0.07872485, -0.16312113,  0.01126234,  0.10397979,
         0.10897624, -0.15663338, -0.027535  ,  0.15346867, -0.10555597],
       [-0.22865885, -0.05687773, -0.4292755 , -0.18598668, -0.1306847 ,
        -0.1713601 , -0.15924251, -0.5382505 ,  0.13520314,  0.26133618],
       [ 0.0414186 , -0.50197387, -0.10253269,  0.06832526,  0.17021182,
        -0.16432276, -0.18056251,  0.0154653 ,  0.2527599 , -0.06593686],
       [ 0.04053664, -0.00842246,  0.42842177,  0.11242062, -0.4331866 ,
         0.19377382,  0.09016499,  0.04691394, -0.11437949,  0.17720228],
       [-0.17199963, -0.13072729, -0.18012999, -0.01277473, -0.03101398,
        -0.28535283, -0.2329935 ,  0.09979966, -0.10311501, -0.6843366 ],
       [-0.06416824,  0.0452911 , -0.08261861,  0.03708746, -0.01684321,
        -0.03358625,  0.19146223,  0.19768523, -0.59155446,  0.07942385],
       [ 0.15184797,  0.09090338,  0.05051003,  0.02499516, -0.17239273,
         0.12053986,  0.09335634,  0.09209993

In [488]:
for i in range(sec_dW_h3.shape[0]):
    for j in range(sec_dW_h3.shape[1]):
        if (sec_dW_h3[i, j] == 0):
            print((i, j))


(4, 132)
(4, 133)
(4, 134)
(4, 135)
(4, 136)
(4, 137)
(4, 138)
(4, 139)
(4, 140)
(4, 141)
(4, 142)
(4, 143)
(4, 144)
(4, 145)
(4, 146)
(4, 147)
(4, 148)
(4, 149)
(4, 150)
(4, 151)
(4, 152)
(4, 153)
(4, 154)
(4, 155)
(4, 156)
(4, 157)
(4, 158)
(4, 159)
(4, 160)
(4, 161)
(4, 162)
(4, 163)
(4, 164)
(4, 165)
(4, 166)
(4, 167)
(4, 168)
(4, 169)
(4, 170)
(4, 171)
(4, 172)
(4, 173)
(4, 174)
(4, 175)
(4, 176)
(4, 177)
(4, 178)
(4, 179)
(4, 180)
(4, 181)
(4, 182)
(4, 183)
(4, 184)
(4, 185)
(4, 186)
(4, 187)
(4, 188)
(4, 189)
(4, 190)
(4, 191)
(5, 0)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 5)
(5, 6)
(5, 7)
(5, 8)
(5, 9)
(5, 10)
(5, 11)
(5, 12)
(5, 13)
(5, 14)
(5, 15)
(5, 16)
(5, 17)
(5, 18)
(5, 19)
(5, 20)
(5, 21)
(5, 22)
(5, 23)
(5, 24)
(5, 25)
(5, 26)
(5, 27)
(5, 28)
(5, 29)
(5, 30)
(5, 31)
(5, 32)
(5, 33)
(5, 34)
(5, 35)
(5, 36)
(5, 37)
(5, 38)
(5, 39)
(5, 40)
(5, 41)
(5, 42)
(5, 43)
(5, 44)
(5, 45)
(5, 46)
(5, 47)
(5, 48)
(5, 49)
(5, 50)
(5, 51)
(5, 52)
(5, 53)
(5, 54)
(5, 55)
(5, 56)
(5, 57)
(5, 58

In [467]:
secondDeriv @ (np.power(X_h3, 2)).transpose()

array([[0.03939096, 0.17403751, 0.04565113, 0.17291511, 0.38332242,
        0.06735595, 0.00536089, 0.25539306, 0.00932086, 0.15036425,
        0.04886765, 0.03530781, 0.05576491, 0.34312351, 0.177838  ,
        0.28696043, 0.257951  , 0.17438455, 0.18117758, 0.40529914,
        0.28325499, 0.35089158, 0.26192561, 0.28747742, 0.08380279,
        0.03822217, 0.35862506, 0.32054733, 0.05124833, 0.22267939],
       [0.02559275, 0.09580182, 0.03315677, 0.12924703, 0.21048307,
        0.03666973, 0.00402958, 0.22690107, 0.00737689, 0.09993452,
        0.03213764, 0.03026942, 0.05298042, 0.18586983, 0.18338464,
        0.23299316, 0.16123059, 0.11965974, 0.12189783, 0.28442248,
        0.17355462, 0.23869668, 0.16810969, 0.20882943, 0.06037101,
        0.01835679, 0.29443415, 0.24837976, 0.03669211, 0.09568675],
       [0.02843031, 0.12707935, 0.0340202 , 0.16069451, 0.31838612,
        0.04807877, 0.00415794, 0.22216044, 0.00819058, 0.12033253,
        0.0392005 , 0.030814  , 0.05662853, 0.

In [468]:
secondDeriv

array([[0.08129165, 0.08099355, 0.11136736, 0.10020419, 0.16011681,
        0.12106194, 0.1217803 , 0.11143239, 0.12423404, 0.06844452],
       [0.08154887, 0.11398878, 0.04919821, 0.11006171, 0.05344237,
        0.07369288, 0.07312171, 0.0824447 , 0.05583661, 0.1088288 ],
       [0.05732639, 0.09019201, 0.06213767, 0.13564766, 0.10157736,
        0.11050202, 0.07963081, 0.10848068, 0.12763672, 0.05949145],
       [0.09546064, 0.11584098, 0.10534928, 0.11225575, 0.11581934,
        0.08964838, 0.10190972, 0.12004157, 0.11446737, 0.09621802],
       [0.13663932, 0.09097925, 0.12538441, 0.05520005, 0.06155773,
        0.07865579, 0.09288255, 0.07151454, 0.06691564, 0.1221777 ],
       [0.08724271, 0.07482975, 0.10121986, 0.07023607, 0.09101557,
        0.08350739, 0.0875215 , 0.08533729, 0.08762937, 0.07596107],
       [0.06884168, 0.07092754, 0.06893764, 0.0896709 , 0.07380006,
        0.09863162, 0.07544874, 0.08216948, 0.09870972, 0.06663395],
       [0.08822091, 0.08877331, 0.0765252

In [391]:
sec_dX_out_activation

array([[0.07851178, 0.09882029, 0.0850205 , 0.07965109, 0.07839628,
        0.08521209, 0.08690832, 0.08213713, 0.08329813, 0.07912449],
       [0.11457875, 0.1036816 , 0.12397347, 0.112069  , 0.1137497 ,
        0.11533497, 0.11344562, 0.10655345, 0.11215007, 0.11594708],
       [0.0860294 , 0.09972635, 0.10078521, 0.08638185, 0.08785372,
        0.09303362, 0.09541367, 0.08533631, 0.08931872, 0.08769513],
       [0.08072495, 0.08508569, 0.08296068, 0.08706778, 0.07977836,
        0.08297727, 0.08407279, 0.08729374, 0.08055197, 0.0821758 ],
       [0.10308903, 0.0898665 , 0.09063742, 0.09934808, 0.10458279,
        0.09335135, 0.09565645, 0.09894096, 0.10255354, 0.09897825],
       [0.06939834, 0.07053644, 0.06790429, 0.06958378, 0.06997633,
        0.07059859, 0.06786172, 0.07209293, 0.06840718, 0.06935353],
       [0.09497982, 0.09674913, 0.09422369, 0.09185681, 0.09502522,
        0.09518936, 0.09574428, 0.09237164, 0.09542642, 0.09448305],
       [0.09477684, 0.08931504, 0.0891571

In [392]:
dX_out_activation

array([[ 0.00769255, -0.09824003,  0.00785252,  0.00859352,  0.0083511 ,
         0.00810397,  0.00908745,  0.00847561,  0.00886286,  0.00814857],
       [ 0.01758987,  0.01195849,  0.02035257,  0.01369734,  0.01657356,
         0.01655109,  0.01240908,  0.01401676,  0.01022589,  0.01517742],
       [ 0.00941525,  0.01264992,  0.01118961,  0.0089363 ,  0.01026279,
         0.00990905,  0.01008129,  0.00871199,  0.00865436,  0.00924029],
       [ 0.00989464,  0.01481314,  0.00813411,  0.01122807,  0.00938116,
         0.00847784,  0.01218058,  0.00939203,  0.01387687,  0.00992984],
       [ 0.01155287,  0.00781734,  0.00857989,  0.01121983, -0.09506167,
         0.00997707,  0.00681124,  0.01307784,  0.00697694,  0.01099607],
       [ 0.00770028,  0.01062332,  0.00573959,  0.00730202,  0.00712303,
         0.00632202, -0.08497115,  0.00666725,  0.00977175,  0.00710836],
       [ 0.01118536,  0.01045691,  0.01050372,  0.00996545,  0.0116628 ,
         0.01079212,  0.00900454,  0.01103507

In [469]:
sec_dW_out

array([[0.00523221, 0.02524758, 0.00796178, 0.0138278 , 0.05478087,
        0.03493539, 0.000961  , 0.03609226, 0.0041682 , 0.07784291,
        0.07404246, 0.00336033, 0.01686973, 0.02971755, 0.04814344,
        0.04729376, 0.04774421, 0.01923202, 0.02821212, 0.04529843,
        0.04161384, 0.04438416, 0.04126019, 0.01752703, 0.03759715,
        0.02278165, 0.04163171, 0.03837785, 0.0118374 , 0.04695169],
       [0.00606789, 0.03208862, 0.00846642, 0.01467448, 0.06594937,
        0.03856681, 0.00096492, 0.04820353, 0.00474035, 0.0868346 ,
        0.07975745, 0.00403007, 0.02633144, 0.03380757, 0.06171382,
        0.06576706, 0.05577917, 0.02916016, 0.03852643, 0.04504763,
        0.05506587, 0.05214361, 0.05266735, 0.02015393, 0.04467566,
        0.03365938, 0.04813752, 0.04804354, 0.01472315, 0.05826697],
       [0.00470869, 0.02359999, 0.00700284, 0.01317286, 0.04973064,
        0.0288627 , 0.00083308, 0.03321427, 0.00421267, 0.07724568,
        0.07391726, 0.00345112, 0.01792559, 0.

In [472]:
W_h3_step

array([[-0.01661504, -0.01406964, -0.00611857, ..., -0.01810993,
        -0.02486411, -0.04220246],
       [-0.04646314, -0.03933575, -0.02616424, ..., -0.03927936,
        -0.02699415, -0.04588016],
       [-0.00758266, -0.02149798, -0.01745052, ..., -0.01970626,
        -0.01185741, -0.00915577],
       ...,
       [-0.1       , -0.1       , -0.1       , ..., -0.1       ,
        -0.1       , -0.1       ],
       [-0.1       , -0.1       , -0.1       , ..., -0.1       ,
        -0.1       , -0.1       ],
       [-0.1       , -0.1       , -0.1       , ..., -0.1       ,
        -0.1       , -0.1       ]], dtype=float32)